version: 2
updates:
  - package-ecosystem: npm
    directory: /
    dependency-type: production
    schedule:
      interval: daily
    cooldown:
      default-days: 3
    open-pull-requests-limit: 25
