name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  codeql-sast:
    name: CodeQL SAST scan
    uses: alphagov/govuk-infrastructure/.github/workflows/codeql-analysis.yml@main
    permissions:
      security-events: write

  dependency-review:
    name: Dependency Review scan
    uses: alphagov/govuk-infrastructure/.github/workflows/dependency-review.yml@main

  test:
    name: Test Extension JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Install Dependencies
        shell: bash
        run: npm install

      - name: Lint
        run: npm run lint:js

      - name: Run Jasmine
        run: npm test

  notify-slack-if-failure-on-main:
    needs:
      - codeql-sast
      - dependency-review
      - test
    if: ${{ always() && github.ref == 'refs/heads/main' && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack if failure on main
        uses: alphagov/govuk-infrastructure/.github/actions/report-run-failure@main
        with:
          slack_webhook_url: ${{ secrets.GOVUK_SLACK_WEBHOOK_URL }}
          channel: govuk-whitehall-experience-tech
          message: "GOVUK Browser Extension CI failed on 'main' and blocked the deployment. Investigate!"
