name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-jasmine:
    name: Test Extension JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        shell: bash
        run: npm install

      - name: Run Jasmine
        run: npm test
